#ifndef _LEVELS_H_
#define _LEVELS_H_

static char* levelTable[] = {
	"Unknown Level",
	"Act 1 Rogue Encampment",
	"Act 1 Blood Moor",
	"Act 1 Cold Plains",
	"Act 1 Stony Field",
	"Act 1 Dark Wood",
	"Act 1 Black Marsh",
	"Act 1 Tamoe Highland",
	"Act 1 Den Of Evil",
	"Act 1 Cave Level 1", // Cave In Cold Plains
	"Act 1 Underground Passage Level 1",
	"Act 1 Hole Level 1",
	"Act 1 Pit Level 1",
	"Act 1 Cave Level 2", // Cave In Cold Plains
	"Act 1 Underground Passage Level 2",
	"Act 1 Holy Level 2",
	"Act 1 Pit Level 2",
	"Act 1 Burial Grounds",
	"Act 1 Crypt",
	"Act 1 Mausoleum",
	"Act 1 Forgotten Tower",
	"Act 1 Tower Cellar Level 1",
	"Act 1 Tower Cellar Level 2",
	"Act 1 Tower Cellar Level 3",
	"Act 1 Tower Cellar Level 4",
	"Act 1 Tower Cellar Level 5",
	"Act 1 Monastery Gate",
	"Act 1 Outer Cloister",
	"Act 1 Barracks",
	"Act 1 Jail Level 1",
	"Act 1 Jail Level 2",
	"Act 1 Jail Level 3",
	"Act 1 Inner Cloister",
	"Act 1 Inner Cloister 2",
	"Act 1 Catacombs Level 1",
	"Act 1 Catacombs Level 2",
	"Act 1 Catacombs Level 3",
	"Act 1 Catacombs Level 4",
	"Act 1 Tristram",
	"Act 1 The Secret Cow Level", 

	"Act 2 Lut Gholein",
	"Act 2 Rocky Waste",
	"Act 2 Dry Hills",
	"Act 2 Far Oasis",
	"Act 2 Lost City",
	"Act 2 Valley Of Snakes",
	"Act 2 Canyon Of The Magi",
	"Act 2 Sewers Level 1",
	"Act 2 Sewers Level 2",
	"Act 2 Sewers Level 3",
	"Act 2 Harem Level 1",
	"Act 2 Harem Level 2",
	"Act 2 Palace Cellar Level 1",
	"Act 2 Palace Cellar Level 2",
	"Act 2 Palace Cellar Level 3",
	"Act 2 Stony Tomb Level 1",
	"Act 2 Halls Of The Dead Level 1",
	"Act 2 Halls Of The Dead Level 2",
	"Act 2 Claw Viper Temple Level 1",
	"Act 2 Stony Tomb Level 2",
	"Act 2 Halls Of The Dead Level 3",
	"Act 2 Claw Viper Temple Level 2",
	"Act 2 Maggot Lair Level 1",
	"Act 2 Maggot Lair Level 2",
	"Act 2 Maggot Lair Level 3",
	"Act 2 Ancient Tunnels",
	"Act 2 Tal Rashas Tomb 1",
	"Act 2 Tal Rashas Tomb 2",
	"Act 2 Tal Rashas Tomb 3",
	"Act 2 Tal Rashas Tomb 4",
	"Act 2 Tal Rashas Tomb 5",
	"Act 2 Tal Rashas Tomb 6",
	"Act 2 Tal Rashas Tomb 7",
	"Act 2 Tal Rashas Chamber",
	"Act 2 Arcane Sanctuary",

	"Act 3 Kurast Docks",
	"Act 3 Spider Forest",
	"Act 3 Great Marsh",
	"Act 3 Flayer Jungle",
	"Act 3 Lower Kurast",
	"Act 3 Kurast Bazaar",
	"Act 3 Upper Kurast",
	"Act 3 Kurast Causeway",
	"Act 3 Travincal",
	"Act 3 Archnid Lair",
	"Act 3 Spider Cavern",
	"Act 3 Swampy Pit Level 1",
	"Act 3 Swampy Pit Level 2",
	"Act 3 Flayer Dungeon Level 1",
	"Act 3 Flayer Dungeon Level 2",
	"Act 3 Swampy Pit Level 3",
	"Act 3 Flayer Dungeon Level 3",
	"Act 3 Sewers Level 1",
	"Act 3 Sewers Level 2",
	"Act 3 Ruined Temple",
	"Act 3 Disused Fane",
	"Act 3 Forgotten Reliquary",
	"Act 3 Forgotten Temple",
	"Act 3 Ruined Fane",
	"Act 3 Disused Reliquary",
	"Act 3 Durance Of Hate Level 1",
	"Act 3 Durance Of Hate Level 2",
	"Act 3 Durance Of Hate Level 3", 

	"Act 4 The Pandemonium Fortress",
	"Act 4 Outer Steppes",
	"Act 4 Plains Of Despair",
	"Act 4 City Of The Damned",
	"Act 4 River Of Flame",
	"Act 4 The Chaos Sanctuary",

	"Act 5 Harrogath",
	"Act 5 The Bloody Foothills",
	"Act 5 Frigid Highlands",
	"Act 5 Arreat Plateau",
	"Act 5 Crystalline Passage",
	"Act 5 Frozen River",
	"Act 5 Glacial Trail",
	"Act 5 Drifter Cavern",
	"Act 5 Frozen Tundra",
	"Act 5 The Ancients Way",
	"Act 5 Icy Cellar",
	"Act 5 Arreat Summit",
	"Act 5 Nihlathaks Temple",
	"Act 5 Halls Of Anguish",
	"Act 5 Halls Of Pain",
	"Act 5 Halls Of Vaught",
	"Act 5 Abaddon",
	"Act 5 Pit Of Acheron",
	"Act 5 Infernal Pit",
	"Act 5 Worldstone Keep Level 1",
	"Act 5 Worldstone Keep Level 2",
	"Act 5 Worldstone Keep Level 3",
	"Act 5 Throne Of Destruction",
	"Act 5 Worldstone Keep",
	"Act 5 Matrons Den",
	"Act 5 Forgotten Sands",
	"Act 5 Furnace Of Pain",
	"Act 5 Tristram"
};

#endif  